### ISSUE TITLE
Game Crashes When Summoning Snakes

### ISSUE THREAD

**Issue by PhantomsKeep** [Raspix13/SnekCraft#1]
Hello! First off, wanted to say I absolutely adore your mod. 10/10 big hit with the server I run and its on!!

Some of the patterns when doing the /summon command will crash the player who is summoning snakes in. So far the only bug that's been reported to me is pattern #3 on hognoses. I will say that the server this issue is coming up on is a hybrid, so there's a chance the crashing stems from that. Just wanted to let you know, though!!

(The version is 1.1.0, btw)

**Comment by Raspix13** [comment]
Hi, I'm glad you like it. 
I found the issue and it should be fixed in the next update (1.1.2). You can avoid crashing until the update is released by not summoning snakes patterns or colors that don't exist (since there are 3 patterns for hoggies, the spawn commands should go 0, 1, 2, not 1-3). I'll try getting the update out in a few days.
